// <auto-generated />
using Blogie.data.DataBlog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogie.data.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20231228174252_addDataToDb")]
    partial class addDataToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blogie.core.BlogInfo.BlogData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Details1",
                            Name = "Shahadat",
                            Summary = "Summary1",
                            Thumnail = "~/image/avenue-815297_640.jpg",
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Details2",
                            Name = "Emran",
                            Summary = "Summary2",
                            Thumnail = "~/image/download(1).jpg",
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Details3",
                            Name = "Mahfuz",
                            Summary = "Summary3",
                            Thumnail = "~/image/download.jpg",
                            Title = "Title3"
                        });
                });

            modelBuilder.Entity("Blogie.core.UserInfo.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
